# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Farama Foundation
email: contact@farama.org
description: >- 
  The Farama Foundation is a non-profit organization which promotes reinforcement
  learning through the maintenance of open source libraries such as Gym, the standard
  reinforcement learning API, 
  Pettingzoo, a multiagent reinforcement learning library, and Supersuit, a collection
  of popular Gym wrappers, as well as a number of other open source projects.
  
url: "farama.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
github: https://github.com/Farama-Foundation
twitter: https://twitter.com/FaramaFound
reddit: https://www.reddit.com/r/farama/
discord: https://discord.gg/PfR7a79FpQ

logo: assets/images/farama_solid_white.svg

favicon: assets/images/farama_solid_white.svg

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
google_analytics: G-F8B6SYES1P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

permalink: /:title
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
